name: Back-End CI

on:
  push:
    paths:
      - 'back-end/**'
  pull_request:
    paths:
      - 'back-end/**'
  schedule:
      - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back-end

    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Rodar lint
        run: npm run lint || echo "Lint falhou, mas não bloqueia o build"

      - name: Rodar testes
        run: npm test || echo "Testes não implementados ainda"

      - name: Rodar verificação de vulnerabilidades
        run: npm audit --audit-level=high

      - name: Upload coverage to SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=jaooduartte
            -Dsonar.projectKey=atletica-engenios-backend
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}

  inativar-usuarios-inativos:
    runs-on: ubuntu-latest
    
    steps:
      - name: Requisição para inativar usuários inativos
        run: |
          curl -X POST https://atleticaengenios.onrender.com/api/admin/inativar-inativos