name: Run Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test-backend:
    name: Test Back-End
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências do back-end
        run: npm install
        working-directory: ./back-end

      - name: Rodar testes do back-end
        run: npm test -- --passWithNoTests
        working-directory: ./back-end

  test-frontend:
    name: Test Front-End
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências do front-end
        run: npm install
        working-directory: ./front-end

      - name: Rodar testes do front-end
        run: npm test -- --passWithNoTests
        working-directory: ./front-end

      - name: Criar diretório de testes do front-end
        run: mkdir -p ./front-end/__tests__

      - name: Adicionar teste básico no front-end
        run: echo "describe('Exemplo de teste front-end', () => { it('deve somar corretamente', () => { expect(1 + 2).toBe(3); }); });" > ./front-end/__tests__/sample.test.js

      - name: Criar diretório de testes do back-end
        run: mkdir -p ./back-end/__tests__

      - name: Adicionar teste básico no back-end
        run: echo "describe('Exemplo de teste back-end', () => { it('deve verificar verdadeiro', () => { expect(true).toBe(true); }); });" > ./back-end/__tests__/sample.test.js